### ISSUE TITLE
Gif keyboard 

### ISSUE THREAD

**Issue by gowthamidommeti** [gfycat/gfycat-android-sdk#2]
How can i use this as a gif keyboard.Please help me to use as a custom gif keyboard.

**Comment by trending-sense** [comment]
Hi @gowthamidommeti . Our SDK does not provide an actual Android keyboard implementation, but it does provide a keyboard-like GIF picker Fragment. For more details refer our documentation:
https://developers.gfycat.com/androidsdk/#gfycat-picker-fragment
Thank you!
