### ISSUE TITLE
Gfycat Webp Player doesn't support 64bits devices

### ISSUE THREAD

**Issue by flipy34** [gfycat/gfycat-android-sdk#3]
Hi:

I have just recently integrated Gfycat SDK using also the Gfycat Picker and the Gfycat WebP Player and looks like later one doesn't support 64bits devices if you try to run the app on a device that has 64bit capabilities and with an app that defines 64bits specific shared libraries (aka .so files), it breaks the Picker and everytime that the user navigates to the Gif Picker it crashes with the following Crash.

`Exception java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
rx.internal.schedulers.ScheduledAction.run (ScheduledAction.java:62)
java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:457)
java.util.concurrent.FutureTask.run (FutureTask.java:266)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:301)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
java.lang.Thread.run (Thread.java:764)
arrow_drop_down
Caused by java.lang.UnsatisfiedLinkError: No implementation found for com.gfycat.webp.WebPImage com.gfycat.webp.WebPImage.nativeCreateFromDirectByteBuffer(java.nio.ByteBuffer) (tried Java_com_gfycat_webp_WebPImage_nativeCreateFromDirectByteBuffer and Java_com_gfycat_webp_WebPImage_nativeCreateFromDirectByteBuffer__Ljava_nio_ByteBuffer_2)
com.gfycat.webp.WebPImage.nativeCreateFromDirectByteBuffer (WebPImage.java)
com.gfycat.webp.WebPImage.create (WebPImage.java:79)
com.gfycat.webp.WebPFrameSequence.<init> (WebPFrameSequence.java:39)
com.gfycat.webp.view.GfycatWebpView$ToFrameSequenceDrawable.call (GfycatWebpView.java:365)
com.gfycat.webp.view.GfycatWebpView$ToFrameSequenceDrawable.call (GfycatWebpView.java:352)
rx.internal.operators.OperatorMap$MapSubscriber.onNext (OperatorMap.java:66)
rx.internal.operators.OperatorDelay$1$3.call (OperatorDelay.java:88)
rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call (EventLoopsScheduler.java:187)
rx.internal.schedulers.ScheduledAction.run (ScheduledAction.java:55)
java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:457)
java.util.concurrent.FutureTask.run (FutureTask.java:266)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:301)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
java.lang.Thread.run (Thread.java:764)`

**Comment by dekalo-stanislav** [comment]
Hi @flipy34.

Thank you for your report, we know about this issue.

Currently our sdk do not support 64bit architecture.
We support only 'x86', 'armeabi', 'armeabi-v7a'

This issue reproduced only if your apk contains other `.so` files for architectures not mentioned above.

As hotfix you can exclude 64bit libs from your apk
```
android {

    ...

    packagingOptions {
        // exclude  not supported architectures
        exclude 'lib/arm64-v8a/libYourLibName.so'
        exclude 'lib/x86_64/libYourLibName.so'
        exclude 'lib/mips64/libYourLibName.so'
        exclude 'lib/mips/libYourLibName.so'
    }
    ...
}
```

In this case system will fallback to known architecture.

**Comment by trending-sense** [comment]
We have just released a new SDK build with 64bit support. Please try build number 0.2.0:
```
compile 'com.gfycat.android:gfycat-picker:0.2.0'
```

**Comment by flipy34** [comment]
Using version 0.2.0 works like a charm.
Issue resolved.
Thank you
