### ISSUE TITLE
Build issues for anything newer than 0.3.0

### ISSUE THREAD

**Issue by HebrewToYou** [gfycat/gfycat-android-sdk#9]
Hi folks,

Getting an error building on the latest Android Studio (3.1) with JRE 1.8.0:
`Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
Message{kind=ERROR, text=Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.`

This occurs when pointing our gradle config at any version newer than 0.3.0. We are using the core, picker, and ads-facebook libraries. Reverting back to 0.3.0 allows the build to work without issue. Let me know if you need any more info.

**Comment by dekalo-stanislav** [comment]
Hi @HebrewToYou. 

1. 0.3.0 is very old version, latest one is 0.6.0.
2. We have sample application, see (https://github.com/gfycat/gfycat-android-sdk/tree/master/app).
   Just tried it in Android Studio 3.1 and it works well. See https://github.com/gfycat/gfycat-android-sdk/commit/49b2bd2fc8e7d0abaadf3a2bd1dbf7d99d6a2a37
   
Here's what we need to figure out what is an issue:
1. Please try reproduce issue in our sample project https://github.com/gfycat/gfycat-android-sdk/tree/master/app.
2. Please share your gradle build files, we need to know versions of gradle, android plugin, build tools.
3. Could you send me output from command line build, like `./gradlew clean installDebug`

Hope to resolve your issue soon!

**Comment by HebrewToYou** [comment]
@dekalo-stanislav - It looks like it requires that we update our gradle version to 3+, which we haven't yet done. I got it to build successfully on a feature-branch where we have updated Gradle. I'll make sure this update is tied to that. Thanks!
